Added error handling for env variables
farsightsec/nmsg-relay pull request #8
Opened 2023-11-15 20:30 UTC by dvladi77

2023-11-17 18:27 UTC, cmikk requested changes

2023-11-17 18:27 UTC, cmikk commented on config.go
> +		println(name, "triggered the following error: ", err.Error())
This should use `log.Fatal`

I would also like to explore alternative approaches to error handling from the `env.ErrorHandler` injection, possibly involving a separate `env.Parse()` stage to collect error reporting at one point, with the `env.*Var` functions merely registering their values.

2023-11-17 18:31 UTC, dvladi77 commented on config.go
> +		println(name, "triggered the following error: ", err.Error())
I considered log.Fatal, but decided in favor of commanLine println, as this error is similar to flag error. log prints in log format with timestamp, etc. I can work on env reworking

2023-11-28 00:08 UTC, shw700 approved these changes

2023-12-04 20:07 UTC, merged